server:
  port: 8080
  servlet:
    context-path: /jms

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp

  datasource:
    url: jdbc:mysql://47.100.116.193:3306/student?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

mybatis:
  type-aliases-package: com.gxun.jms.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
